evolution_mappings = {
    "Poseidon (Tyrant of the Seas)": "Poseidon (Tyrant of the Seas)",
    "Poseidon (Poseidon)": "Poseidon (Poseidon)",
    "Gol D. Roger": "Roger (Pirate King)",
    "Roger (Gol D. Roger)": "Roger (Gol D. Roger)",
    "Avdol": "Avdo (Magician's Red)",
    "Avdo (Avdol)": "Avdo (Avdol)",
    "Harribu(Shark Empress)": "Harribu(Shark Empress)",
    "Harribu (Harribel)": "Harribu (Harribel)",
    "Kisame": "Kizume (Tailless Beast)",
    "Kizume (Kisame)": "Kizume (Kisame)",
    "Daki": "Daky (Obi)",
    "Flamingo(Awakened)": "Flamingo(Awakened)",
    "Geto": "Getu (Maximum)",
    "Homura Akemi": "Homuru (Time Traveller)",
    "Homuru": "Homuru (Time Traveller)",
    "Homura": "Homuru (Time Traveller)",
    "Esdeath": "Ice Queen (Empire's Strongest)",
    "Jellal": "Jelly (Heaven)",
    "Heaven Ascension DIO": "JIO (Over Heaven)",
    "Dio": "JIO (Over Heaven)",
    "Jio": "JIO (Over Heaven)",
    "Kento": "Kent (Overtime)",
    "Kisuke": "Kisoko (Bankai)",
    "Kit (Focus)": "Kit (Focus)",
    "Kit (Frenzy)": "Kit (Frenzy)",
    "Kit (Lethal)": "Kit (Lethal)",
    "Kit (Precision)": "Kit (Precision)",
    "Boros (Meteoric Burst)": "Lord Boron",
    "Luci (Celestial) (Lucy)": "Luci (Celestial) (Lucy)",
    "Lelouch Lamperouge": "Lulu (Geass)",
    "Merlin": "Merlyn (Infinity)",
    "Piccolo (Nameless)": "Piccoru (Nameless)",
    "Shisui": "Shisu (Flicker)",
    "Skull Knight (King)": "Skull Knight (King)",
    "Yamamoto (Bankai)": "Yamomoto (Hellfire)",
    "Boron (Boros)": "Boron (Boros)",
    "Daki": "Daky",
    "Denjy (Denji)": "Denjy (Denji)",
    "Fire Fist (Ace)": "Fire Fist (Ace)",
    "Ace": "Fire Fist (Ace)",
    "Flamingo (Doflamingo)": "Flamingo (Doflamingo)",
    "Getu (Geto)": "Getu (Geto)",
    "Homura Akemi": "Homuru",
    "Ice Queen (Esdeath)": "Ice Queen (Esdeath)",
    "Ichi(Full Hollow)": "Ichi(Full Hollow)",
    "Jelly (Jellal)": "Jelly (Jellal)",
    "Lulu (Lelouch Lamperouge)": "Lulu (Lelouch Lamperouge)",
    "Merlyn (Merlin)": "Merlyn (Merlin)",
    "Piccolo (Namekian Fusion)": "Piccoru (Fusion)",
    "Renzi (Renji)": "Renzi (Renji)",
    "Shisu (Shisui)": "Shisu (Shisui)",
    "Skull Knight": "Skull Knight",
    "Veku": "Veko",
    "Yamomoto (Yamamoto)": "Yamomoto (Yamamoto)",
    "Aizo (Betrayal) (Aizen)": "Aizo (Betrayal) (Aizen)",
    "Aizen (2nd Fusion Hōgyoku)": "Aizo (Chrysalis)",
    "Aizen (Final Fusion Hōgyoku)": "Aizo (Final)",
    "Aizen (4th Fusion Hōgyoku)": "Aizo (Fusion)",
    "Akena(Fallen Angel)": "Akena(Fallen Angel)",
    "Aki": "Akin (Contract)",
    "Akaza": "Akoku (Destruction)",
    "All Force(Symbol of Peace)": "All Force(Symbol of Peace)",
    "Angel Devil": "Angel (Devil)",
    "Aokiji": "Aokijo (Blue Pheasant)",
    "Arima": "Ariva (Reaper)",
    "Asuna Yuuki": "Asuno (Flash)",
    "Bakugo (Howitzer)": "Bakugo (Howitzer)",
    "Bang(Silver Fang)": "Bang(Silver Fang)",
    "Broke(Soul King)": "Broke(Soul King)",
    "Carrot": "Carrot (Sulong)",
    "Perfect Cell": "Cel (Perfect)",
    "Super Perfect Cell": "Cel (SUPER PERFECT)",
    "Denji": "Chainsaw (Hybrid)",
    "Chairman Neteru (Isaac Netero)": "Chairman Neteru (Isaac Netero)",
    "Charmy Pappitson": "Charmi (Sheep)",
    "Coyote Starrk": "Coyote (Primera)",
    "Gildarts (Ace)": "Crush (Ace)",
    "Diane": "Dany (Creation)",
    "Dark Asto (Black Asta)": "Dark Asto (Black Asta)",
    "Deku (Blackwhip)": "Dezu (Vigilante)",
    "Emperor Whitehair": "Emperor Whitehair",
    "Endeavor (Hellflame)": "Endeavor (Hellflame)",
    "Erein(Founder)": "Erein(Founder)",
    "Ermes": "Ermo (Duplicate)",
    "Eta (One-Eye)": "Eta (One-Eye)",
    "Erza": "Ezra (Lightning)",
    "Ezra(True Heart)": "Ezra(True Heart)",
    "Erza": "Ezra (Valkyrie)",
    "Fleet Admiral Akano (Akainu)": "Fleet Admiral Akano (Akainu)",
    "Fujitora (Admiral)": "Fuji (Admiral)",
    "Genos": "Geno (Incinerate)",
    "Ghiaccio (White Album)": "Ghacco (Album)",
    "Ging(Sacred Spear)": "Ging(Sacred Spear)",
    "Goju(Six Eyes)": "Goju(Six Eyes)",
    "Golden Frieza": "Golden Freezo (Emperor)",
    "Gone (": "Gone (",
    "Gowther": "Gowthy (Invasion)",
    "Gray(Devil Slayer)": "Gray(Devil Slayer)",
    "Ban": "Greed (Hunt)",
    "Griffin(Ascension)": "Griffin(Ascension)",
    "Griffin(Darkness)": "Griffin(Darkness)",
    "Griffin(Reincarnation)": "Griffin(Reincarnation)",
    "Guts (Berserk)": "Guts (Berserk)",
    "Gyutaro (Upper Moon)": "Gyutaru (Moon)",
    "Haku": "Haka (Reflection)",
    "Hanje (Captain)": "Hanje (Captain)",
    "Hawk(Fierce Wings)": "Hawk(Fierce Wings)",
    "Pannacotta Fugo (Rage)": "Haze (Rage)",
    "Heathcliff (Admin)": "Heathcliff (Admin)",
    "Weather Report (Heavy Weather)": "Heavy Weather",
    "Himeno": "Hime (Ghost)",
    "Ichi(Final Dusk)": "Ichi(Final Dusk)",
    "Issai(Boosted Gear)": "Issai(Boosted Gear)",
    "Itachi": "Itochi (Susanoo)",
    "Jokujo(The World)": "Jokujo(The World)",
    "Jolyne": "Jolyna (Determination)",
    "Julio(Wizard King)": "Julio(Wizard King)",
    "Juuzou": "Juozu (Joker)",
    "Kenpachi": "Kenpaki (Maniac)",
    "King": "King (Sloth)",
    "King Meruam (Meruem)": "King Meruam (Meruem)",
    "Kirito": "Kiroto (Dual)",
    "Killua": "Kizzua (Godspeed)",
    "Klein": "Klay (Bachelor)",
    "Kobeni": "Kobeno (Scared)",
    "Cat)": "Kuneko(Hell",
    "Kyoka Sakura": "Kyoka (Scarlet Lance)",
    "Law (ROOM)": "Lao (ROOM)",
    "Leafa": "Leafy (Sylph)",
    "Legendary Brulo (Broly)": "Legendary Brulo (Broly)",
    "Levy Ackman (Levi)": "Levy Ackman (Levi)",
    "Lucky(Thunder Fiend)": "Lucky(Thunder Fiend)",
    "Luffy (Gear 4)": "Luffo (Gear IV)",
    "Madoko(Salvation)": "Madoko(Salvation)",
    "Mami Tomoe": "Mamy (Holy)",
    "Madara": "Marada (Founder)",
    "Mash (Muscles)": "Mash (Muscles)",
    "Megomu(Chimera Shadow)": "Megomu(Chimera Shadow)",
    "Meliodas (Assault Mode)": "Melio (Assault)",
    "Bofoi": "Metal Knight (Arsenal)",
    "Mirka(Tiger Bunny)": "Mirka(Tiger Bunny)",
    "Mochi Charlot (Katakuri)": "Mochi Charlot (Katakuri)",
    "Moriu(Shadow Lord)": "Moriu(Shadow Lord)",
    "Natsu": "Natzo (Lightning Dragon Mode)",
    "Nami": "Navi (Thief)",
    "Noel(Valkyrie Armor)": "Noel(Valkyrie Armor)",
    "Noruto(Beast Cloak)": "Noruto(Beast Cloak)",
    "Ai Hoshino": "Oshy (Idol)",
    "Peruna(Ghost Princess)": "Peruna(Ghost Princess)",
    "Neferpitou": "Pito (Terpsichora)",
    "Power (Fiend)": "Power (Fiend)",
    "Pride (Day) (Escanor)": "Pride (Day) (Escanor)",
    "Escanor": "Pride (The One)",
    "Puchi(Heaven)": "Puchi(Heaven)",
    "Puchi(New Moon)": "Puchi(New Moon)",
    "Shanks": "Red Scar (Conqueror)",
    "Rengoku": "Renkoko (ABLAZE)",
    "Ria(Devil Princess)": "Ria(Devil Princess)",
    "Sabo (Flame Emperor)": "Saby (Flame Emperor)",
    "Sayaka Miki": "Sayako (Sapphire Blade)",
    "Sengoku": "Senbodu (Buddha)",
    "Shigaraki": "Shigaruko (Symbol of Fear)",
    "Suì-Fēng": "Soi Fan (Hornet)",
    "Speed-o'-Sound Sonic": "Sonic (Speed)",
    "Sasuke (Storm)": "Sosuke (Storm)",
    "Stain(Hero Slayer)": "Stain(Hero Slayer)",
    "Sukuno (Sukuna)": "Sukuno (Sukuna)",
    "Super Chunks (Trunks)": "Super Chunks (Trunks)",
    "Tengen Uzui": "Tango (God of Flashiness)",
    "(Tatara)": "Tarata (Ignite)",
    "Tatsumaki": "Tatsumiki (Tornado)",
    "Thor (Awakened)": "Thor (Awakened)",
    "Todoroki": "Todorro (Released)",
    "Toshiro": "Toshin (Dragon Lotus)",
    "(Ulquiorra)": "Ulquiro (Resurrección)",
    "Uryu (Antithesis)": "Uru (Antithesis)",
    "Usopp (God)": "Usoap (God)",
    "Usopp": "Usoap (God)",
    "Usoap": "Usoap (God)",
    "Vash the Stampede": "Vas (Cross)",
    "Vegeta (Super Saiyan 2)": "Vegita (Super II)",
    "Yami": "Yamo (Captain)",
    "Yuno": "Yono (Spirit)",
    "Yoshina (Spirit)": "Yoshina (Spirit)",
    "Yuto(Cursed Child)": "Yuto(Cursed Child)",
    "Aizo (Aizen)": "Aizo (Aizen)",
    "Akano (Akainu)": "Akano (Akainu)",
    "Akena (Akeno Himejima)": "Akena (Akeno Himejima)",
    "Akin (Aki)": "Akin (Aki)",
    "All Force": "All Force",
    "Android 21": "Android 21",
    "Angel (Angel Devil)": "Angel (Angel Devil)",
    "Aokijo (Aokiji)": "Aokijo (Aokiji)",
    "Ariva (Arima)": "Ariva (Arima)",
    "Armein (Armin)": "Armein (Armin)",
    "Asto (Asta)": "Asto (Asta)",
    "Asuno (Asuna)": "Asuno (Asuna)",
    "Bakugo (Explosion)": "Bakugo (Explosion)",
    "Bang (Bang)": "Bang (Bang)",
    "Blue Devil (Rin Okumura)": "Blue Devil (Rin Okumura)",
    "Broke (Brook)": "Broke (Brook)",
    "Brulo (Broly)": "Brulo (Broly)",
    "Buggy": "Buggy",
    "Carrot": "Carrot",
    "Chainsaw (Denji)": "Chainsaw (Denji)",
    "Charmi (Charmy Pappitson)": "Charmi (Charmy Pappitson)",
    "Coyote (Coyote Starrk)": "Coyote (Coyote Starrk)",
    "Crush (Gildarts)": "Crush (Gildarts)",
    "Diane": "Dany",
    "Deku (Blackwhip)": "Dezu (Blackwhip)",
    "Diavoro (Diavolo)": "Diavoro (Diavolo)",
    "Emili (Emilia)": "Emili (Emilia)",
    "Endeavor": "Endeavor",
    "Ermo (Ermes)": "Ermo (Ermes)",
    "Eta (Eto)": "Eta (Eto)",
    "Ezra (Erza)": "Ezra (Erza)",
    "Fuji (Fujitora)": "Fuji (Fujitora)",
    "Future Guhon (Future Gohan)": "Future Guhon (Future Gohan)",
    "Genos": "Geno (Overdrive)",
    "Ghacco (Ghiaccio)": "Ghacco (Ghiaccio)",
    "Ging (Gin)": "Ging (Gin)",
    "Goju (Gojo)": "Goju (Gojo)",
    "Golden Freezo (Golden Frieza)": "Golden Freezo (Golden Frieza)",
    "Gon (Adult)": "Gone (Adult)",
    "Gowthy (Gowther)": "Gowthy (Gowther)",
    "Gray": "Gray",
    "Ban": "Greed",
    "Griffin (Griffith)": "Griffin (Griffith)",
    "Guts": "Guts",
    "Gyutaru (Gyutaro)": "Gyutaru (Gyutaro)",
    "Haka (Haku)": "Haka (Haku)",
    "Hanje": "Hanje",
    "Hawk": "Hawk",
    "Pannacotta Fugo": "Haze",
    "Heathcliff": "Heathcliff",
    "Hie (Hiei)": "Hie (Hiei)",
    "Himeno": "Hime",
    "Ichigo (Final Getsuga Tensho)": "Ichi (Dusk)",
    "Inuyashu (Inuyasha)": "Inuyashu (Inuyasha)",
    "Ipo (Ippo)": "Ipo (Ippo)",
    "Issai (Issei Hyoudou)": "Issai (Issei Hyoudou)",
    "Itadoki (Itadori)": "Itadoki (Itadori)",
    "Itachi": "Itochi (Amaterasu)",
    "Jin Mori": "Ji Mo Ri",
    "Jokujo(Serious)": "Jokujo(Serious)",
    "Jolyna (Jolyne)": "Jolyna (Jolyne)",
    "Jozu": "Jozo",
    "Julius": "Julio",
    "Juozu (Juuzou)": "Juozu (Juuzou)",
    "Kenpaki (Kenpachi)": "Kenpaki (Kenpachi)",
    "Kent (Kento)": "Kent (Kento)",
    "King": "King",
    "Kirito": "Kiroto",
    "Kisoko (Kisuke)": "Kisoko (Kisuke)",
    "Kit": "Kit",
    "Killua": "Kizzua (Whirlwind)",
    "Klay (Klein)": "Klay (Klein)",
    "Kobeno (Kobeni)": "Kobeno (Kobeni)",
    "Kumo (Kuma)": "Kumo (Kuma)",
    "Kuneko (Koneko Toujou)": "Kuneko (Koneko Toujou)",
    "Kyoko Sakura": "Kyoka",
    "Law (Heart)": "Lao (Heart)",
    "Leafa": "Leafy",
    "Levy (Levi)": "Levy (Levi)",
    "Luci (Lucy)": "Luci (Lucy)",
    "Lucky (Luck)": "Lucky (Luck)",
    "Luffy": "Luffo (Bounce)",
    "Madoka Kaname": "Madoko",
    "Mami Tomoe": "Mamy",
    "Marada (Madara)": "Marada (Madara)",
    "Mash": "Mash",
    "Megomu (Megumi)": "Megomu (Megumi)",
    "Melio (Meliodas)": "Melio (Meliodas)",
    "Meruam (Meruem)": "Meruam (Meruem)",
    "Metal Knight (Bofoi)": "Metal Knight (Bofoi)",
    "Mirka (Mirko)": "Mirka (Mirko)",
    "Mochi": "Mochi",
    "Moriu (Moria)": "Moriu (Moria)",
    "Natzo (Natsu)": "Natzo (Natsu)",
    "Navi (Nami)": "Navi (Nami)",
    "Nejiri (Nejire)": "Nejiri (Nejire)",
    "Neteru (Isaac Netero)": "Neteru (Isaac Netero)",
    "Noel (Noelle)": "Noel (Noelle)",
    "Ai Hoshino": "Oshy",
    "Peruna (Perona)": "Peruna (Perona)",
    "Pito (Neferpitou)": "Pito (Neferpitou)",
    "Power": "Power",
    "Pride (Night) (Escanor)": "Pride (Night) (Escanor)",
    "Puchi (Enrico Pucci)": "Puchi (Enrico Pucci)",
    "Raylay (Rayleigh)": "Raylay (Rayleigh)",
    "Red Scar (Shanks)": "Red Scar (Shanks)",
    "Renkoko (Rengoku)": "Renkoko (Rengoku)",
    "Ria (Rias Gremory)": "Ria (Rias Gremory)",
    "Roshy (Roshi)": "Roshy (Roshi)",
    "Saby (Sabo)": "Saby (Sabo)",
    "Sabo": "Saby (Sabo)",
    "Saicky (Saiki)": "Saicky (Saiki)",
    "Sayaka Miki": "Sayako",
    "Sengoku": "Senbodu",
    "Shigaruko (Shigaraki)": "Shigaruko (Shigaraki)",
    "Snake Princess (Boa Hancock)": "Snake Princess",
    "Boa Hancock": "Snake Princess",
    "Boa": "Snake Princess",
    "Hancock": "Snake Princess",
    "Fēng)": "Soi Fan (Suì",
    "Speed-o'-Sound Sonic": "Sonic",
    "Sasuke (Hebi)": "Sosuke (Hebi)",
    "Stain": "Stain",
    "Tengen Uzui": "Tango (Score)",
    "Tango (Tengen)": "Tango (Tengen)",
    "Tarata (Tatara)": "Tarata (Tatara)",
    "Tatsumaki": "Tatsumiki",
    "Tatsumo (Tatsumi)": "Tatsumo (Tatsumi)",
    "Temori": "Temori",
    "Thor": "Thor",
    "Toby (Tobi)": "Toby (Tobi)",
    "Todoroki": "Todorro (Half)",
    "Toshin (Toshiro)": "Toshin (Toshiro)",
    "Ulquiro (Ulquiorra)": "Ulquiro (Ulquiorra)",
    "Unohona (Retsu Unohana)": "Unohona (Retsu Unohana)",
    "Uru": "Uru",
    "Usopp (Timeskip)": "Usoap (Timeskip)",
    "Vash the Stampede": "Vas",
    "Vegeta (Super Saiyan)": "Vegita (Super)",
    "Weather (Weather Report)": "Weather (Weather Report)",
    "Whitehair": "Whitehair",
    "Yamo (Yami)": "Yamo (Yami)",
    "Yono (Yuno)": "Yono (Yuno)",
    "Yoshina (Yoshino Himekawa)": "Yoshina (Yoshino Himekawa)",
    "Yuto (Yuta)": "Yuto (Yuta)"
}
